CREATE TABLE `service_record` (
  `serv_Id` varchar(10) NOT NULL,
  `car_Id` varchar(10) NOT NULL,
  `serReName` varchar(255) NOT NULL,
  `serReDate` date NOT NULL,
  `serReDescription` text DEFAULT 'None',
  `serReComments` text DEFAULT 'None',
  `serReWarranty` date NOT NULL,
  `serReStatusWarranty` tinyint(4) DEFAULT NULL,
  `serReDownPayment` int(11) DEFAULT NULL,
  `serReStatus` varchar(45) NOT NULL,
  `serReInitialTotal` decimal(10,0) NOT NULL,
  `serReTotal` decimal(10,0) DEFAULT NULL,
  `serReTotalLeft` decimal(10,0) DEFAULT NULL,
  `serRe_Approved_By` varchar(45) DEFAULT NULL,
  `serRe_milage_at_Service` int(11) DEFAULT NULL,
  `serRe_Finished_Date` date DEFAULT NULL,
  `tic_Id` varchar(45) DEFAULT NULL,
  `mat_Id` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`serv_Id`),
  KEY `car_Id` (`car_Id`),
  KEY `mat_Id` (`mat_Id`),
  CONSTRAINT `service_record_ibfk_1` FOREIGN KEY (`car_Id`) REFERENCES `car` (`car_Id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4